create table Cache (ID_Statut integer, ID_Type integer, NUMERO integer not null auto_increment, descriptionTechnique varchar(100), descriptionTextuelle varchar(100), informationsGeolocalisation varchar(100), rubriqueLibre varchar(100), primary key (NUMERO)) engine=InnoDB;
create table Statut (ID_Statut integer not null auto_increment, Texte varchar(50), primary key (ID_Statut)) engine=InnoDB;
create table Type (ID_Type integer not null auto_increment, Texte varchar(50), primary key (ID_Type)) engine=InnoDB;
alter table Cache add constraint UK62xkb7i2a9oy0mq5lvt014x47 unique (ID_Statut);
alter table Cache add constraint UKsuwofma9u4b4t6h3lefqftmq8 unique (ID_Type);
alter table Cache add constraint FK4g92qulrgjbexfylmq5xstfk7 foreign key (ID_Statut) references Statut (ID_Statut);
alter table Cache add constraint FK1ham39cdnqpa86lqysyp43lpm foreign key (ID_Type) references Type (ID_Type);
create table Cache (ID_Statut integer, ID_Type integer, NUMERO integer not null auto_increment, descriptionTechnique varchar(100), descriptionTextuelle varchar(100), informationsGeolocalisation varchar(100), rubriqueLibre varchar(100), primary key (NUMERO)) engine=InnoDB;
create table Statut (ID_Statut integer not null auto_increment, Texte varchar(50), primary key (ID_Statut)) engine=InnoDB;
create table Type (ID_Type integer not null auto_increment, Texte varchar(50), primary key (ID_Type)) engine=InnoDB;
alter table Cache add constraint UK62xkb7i2a9oy0mq5lvt014x47 unique (ID_Statut);
alter table Cache add constraint UKsuwofma9u4b4t6h3lefqftmq8 unique (ID_Type);
alter table Cache add constraint FK4g92qulrgjbexfylmq5xstfk7 foreign key (ID_Statut) references Statut (ID_Statut);
alter table Cache add constraint FK1ham39cdnqpa86lqysyp43lpm foreign key (ID_Type) references Type (ID_Type);
create table Cache (ID_Statut integer, ID_Type integer, NUMERO integer not null auto_increment, descriptionTechnique varchar(100), descriptionTextuelle varchar(100), informationsGeolocalisation varchar(100), rubriqueLibre varchar(100), primary key (NUMERO)) engine=InnoDB;
create table Statut (ID_Statut integer not null auto_increment, Texte varchar(50), primary key (ID_Statut)) engine=InnoDB;
create table Type (ID_Type integer not null auto_increment, Texte varchar(50), primary key (ID_Type)) engine=InnoDB;
alter table Cache add constraint UK62xkb7i2a9oy0mq5lvt014x47 unique (ID_Statut);
alter table Cache add constraint UKsuwofma9u4b4t6h3lefqftmq8 unique (ID_Type);
alter table Cache add constraint FK4g92qulrgjbexfylmq5xstfk7 foreign key (ID_Statut) references Statut (ID_Statut);
alter table Cache add constraint FK1ham39cdnqpa86lqysyp43lpm foreign key (ID_Type) references Type (ID_Type);
create table Cache (ID_Statut integer, ID_Type integer, NUMERO integer not null auto_increment, descriptionTechnique varchar(100), descriptionTextuelle varchar(100), informationsGeolocalisation varchar(100), rubriqueLibre varchar(100), primary key (NUMERO)) engine=InnoDB;
create table Statut (ID_Statut integer not null auto_increment, Texte varchar(50), primary key (ID_Statut)) engine=InnoDB;
create table Type (ID_Type integer not null auto_increment, Texte varchar(50), primary key (ID_Type)) engine=InnoDB;
alter table Cache add constraint UK62xkb7i2a9oy0mq5lvt014x47 unique (ID_Statut);
alter table Cache add constraint UKsuwofma9u4b4t6h3lefqftmq8 unique (ID_Type);
alter table Cache add constraint FK4g92qulrgjbexfylmq5xstfk7 foreign key (ID_Statut) references Statut (ID_Statut);
alter table Cache add constraint FK1ham39cdnqpa86lqysyp43lpm foreign key (ID_Type) references Type (ID_Type);
create table Cache (ID_Statut integer, ID_Type integer, NUMERO integer not null auto_increment, descriptionTechnique varchar(100), descriptionTextuelle varchar(100), informationsGeolocalisation varchar(100), rubriqueLibre varchar(100), primary key (NUMERO)) engine=InnoDB;
create table Statut (ID_Statut integer not null auto_increment, Texte varchar(50), primary key (ID_Statut)) engine=InnoDB;
create table Type (ID_Type integer not null auto_increment, Texte varchar(50), primary key (ID_Type)) engine=InnoDB;
alter table Cache add constraint UK62xkb7i2a9oy0mq5lvt014x47 unique (ID_Statut);
alter table Cache add constraint UKsuwofma9u4b4t6h3lefqftmq8 unique (ID_Type);
alter table Cache add constraint FK4g92qulrgjbexfylmq5xstfk7 foreign key (ID_Statut) references Statut (ID_Statut);
alter table Cache add constraint FK1ham39cdnqpa86lqysyp43lpm foreign key (ID_Type) references Type (ID_Type);
create table Cache (ID_Statut integer, ID_Type integer, NUMERO integer not null auto_increment, descriptionTechnique varchar(100), descriptionTextuelle varchar(100), informationsGeolocalisation varchar(100), rubriqueLibre varchar(100), primary key (NUMERO)) engine=InnoDB;
create table Statut (ID_Statut integer not null auto_increment, Texte varchar(50), primary key (ID_Statut)) engine=InnoDB;
create table Type (ID_Type integer not null auto_increment, Texte varchar(50), primary key (ID_Type)) engine=InnoDB;
alter table Cache add constraint UK62xkb7i2a9oy0mq5lvt014x47 unique (ID_Statut);
alter table Cache add constraint UKsuwofma9u4b4t6h3lefqftmq8 unique (ID_Type);
alter table Cache add constraint FK4g92qulrgjbexfylmq5xstfk7 foreign key (ID_Statut) references Statut (ID_Statut);
alter table Cache add constraint FK1ham39cdnqpa86lqysyp43lpm foreign key (ID_Type) references Type (ID_Type);
create table Cache (ID_Statut integer, ID_Type integer, NUMERO integer not null auto_increment, descriptionTechnique varchar(100), descriptionTextuelle varchar(100), informationsGeolocalisation varchar(100), rubriqueLibre varchar(100), primary key (NUMERO)) engine=InnoDB;
create table Statut (ID_Statut integer not null auto_increment, Texte varchar(50), primary key (ID_Statut)) engine=InnoDB;
create table Type (ID_Type integer not null auto_increment, Texte varchar(50), primary key (ID_Type)) engine=InnoDB;
alter table Cache add constraint UK62xkb7i2a9oy0mq5lvt014x47 unique (ID_Statut);
alter table Cache add constraint UKsuwofma9u4b4t6h3lefqftmq8 unique (ID_Type);
alter table Cache add constraint FK4g92qulrgjbexfylmq5xstfk7 foreign key (ID_Statut) references Statut (ID_Statut);
alter table Cache add constraint FK1ham39cdnqpa86lqysyp43lpm foreign key (ID_Type) references Type (ID_Type);
create table Cache (ID_Statut integer, ID_Type integer, NUMERO integer not null auto_increment, descriptionTechnique varchar(100), descriptionTextuelle varchar(100), informationsGeolocalisation varchar(100), rubriqueLibre varchar(100), primary key (NUMERO)) engine=InnoDB;
create table Statut (ID_Statut integer not null auto_increment, Texte varchar(50), primary key (ID_Statut)) engine=InnoDB;
create table Type (ID_Type integer not null auto_increment, Texte varchar(50), primary key (ID_Type)) engine=InnoDB;
alter table Cache add constraint UK62xkb7i2a9oy0mq5lvt014x47 unique (ID_Statut);
alter table Cache add constraint UKsuwofma9u4b4t6h3lefqftmq8 unique (ID_Type);
alter table Cache add constraint FK4g92qulrgjbexfylmq5xstfk7 foreign key (ID_Statut) references Statut (ID_Statut);
alter table Cache add constraint FK1ham39cdnqpa86lqysyp43lpm foreign key (ID_Type) references Type (ID_Type);
create table Cache (NUMERO integer not null auto_increment, fk_Cache_Statut integer, fk_Cache_Type integer, descriptionTechnique varchar(100), descriptionTextuelle varchar(100), informationsGeolocalisation varchar(100), rubriqueLibre varchar(100), primary key (NUMERO)) engine=InnoDB;
create table Statut (ID_Statut integer not null auto_increment, Texte varchar(50), primary key (ID_Statut)) engine=InnoDB;
create table Type (ID_Type integer not null auto_increment, Texte varchar(50), primary key (ID_Type)) engine=InnoDB;
alter table Cache add constraint FKb3ba1m83ok6lns3gm5hpw93hw foreign key (fk_Cache_Statut) references Statut (ID_Statut);
alter table Cache add constraint FKruvu6dsuvg2py4iuttwr8k12n foreign key (fk_Cache_Type) references Type (ID_Type);
create table Cache (NUMERO integer not null auto_increment, fk_Cache_Statut integer, fk_Cache_Type integer, descriptionTechnique varchar(100), descriptionTextuelle varchar(100), informationsGeolocalisation varchar(100), rubriqueLibre varchar(100), primary key (NUMERO)) engine=InnoDB;
create table Statut (ID_Statut integer not null auto_increment, Texte varchar(50), primary key (ID_Statut)) engine=InnoDB;
create table Type (ID_Type integer not null auto_increment, Texte varchar(50), primary key (ID_Type)) engine=InnoDB;
alter table Cache add constraint FKb3ba1m83ok6lns3gm5hpw93hw foreign key (fk_Cache_Statut) references Statut (ID_Statut);
alter table Cache add constraint FKruvu6dsuvg2py4iuttwr8k12n foreign key (fk_Cache_Type) references Type (ID_Type);
create table Cache (NUMERO integer not null auto_increment, fk_Cache_Statut integer, fk_Cache_Type integer, descriptionTechnique varchar(100), descriptionTextuelle varchar(100), informationsGeolocalisation varchar(100), rubriqueLibre varchar(100), primary key (NUMERO)) engine=InnoDB;
create table Statut (ID_Statut integer not null auto_increment, Texte varchar(50), primary key (ID_Statut)) engine=InnoDB;
create table Type (ID_Type integer not null auto_increment, Texte varchar(50), primary key (ID_Type)) engine=InnoDB;
alter table Cache add constraint FKb3ba1m83ok6lns3gm5hpw93hw foreign key (fk_Cache_Statut) references Statut (ID_Statut);
alter table Cache add constraint FKruvu6dsuvg2py4iuttwr8k12n foreign key (fk_Cache_Type) references Type (ID_Type);
create table Cache (NUMERO integer not null auto_increment, fk_Cache_Statut integer, fk_Cache_Type integer, descriptionTechnique varchar(100), descriptionTextuelle varchar(100), informationsGeolocalisation varchar(100), rubriqueLibre varchar(100), primary key (NUMERO)) engine=InnoDB;
create table Statut (ID_Statut integer not null auto_increment, Texte varchar(50), primary key (ID_Statut)) engine=InnoDB;
create table Type (ID_Type integer not null auto_increment, Texte varchar(50), primary key (ID_Type)) engine=InnoDB;
alter table Cache add constraint FKb3ba1m83ok6lns3gm5hpw93hw foreign key (fk_Cache_Statut) references Statut (ID_Statut);
alter table Cache add constraint FKruvu6dsuvg2py4iuttwr8k12n foreign key (fk_Cache_Type) references Type (ID_Type);
create table Cache (NUMERO integer not null auto_increment, fk_Cache_Statut integer, fk_Cache_Type integer, descriptionTechnique varchar(100), descriptionTextuelle varchar(100), informationsGeolocalisation varchar(100), rubriqueLibre varchar(100), primary key (NUMERO)) engine=InnoDB;
create table Statut (ID_Statut integer not null auto_increment, Texte varchar(50), primary key (ID_Statut)) engine=InnoDB;
create table Type (ID_Type integer not null auto_increment, Texte varchar(50), primary key (ID_Type)) engine=InnoDB;
alter table Cache add constraint FKb3ba1m83ok6lns3gm5hpw93hw foreign key (fk_Cache_Statut) references Statut (ID_Statut);
alter table Cache add constraint FKruvu6dsuvg2py4iuttwr8k12n foreign key (fk_Cache_Type) references Type (ID_Type);
create table Cache (NUMERO integer not null auto_increment, fk_Cache_Statut integer, fk_Cache_Type integer, descriptionTechnique varchar(100), descriptionTextuelle varchar(100), informationsGeolocalisation varchar(100), rubriqueLibre varchar(100), primary key (NUMERO)) engine=InnoDB;
create table Statut (ID_Statut integer not null auto_increment, Texte varchar(50), primary key (ID_Statut)) engine=InnoDB;
create table Type (ID_Type integer not null auto_increment, Texte varchar(50), primary key (ID_Type)) engine=InnoDB;
alter table Cache add constraint FKb3ba1m83ok6lns3gm5hpw93hw foreign key (fk_Cache_Statut) references Statut (ID_Statut);
alter table Cache add constraint FKruvu6dsuvg2py4iuttwr8k12n foreign key (fk_Cache_Type) references Type (ID_Type);
create table Cache (NUMERO integer not null auto_increment, fk_Cache_Statut integer, fk_Cache_Type integer, descriptionTechnique varchar(100), descriptionTextuelle varchar(100), informationsGeolocalisation varchar(100), rubriqueLibre varchar(100), primary key (NUMERO)) engine=InnoDB;
create table Statut (ID_Statut integer not null auto_increment, Texte varchar(50), primary key (ID_Statut)) engine=InnoDB;
create table Type (ID_Type integer not null auto_increment, Texte varchar(50), primary key (ID_Type)) engine=InnoDB;
alter table Cache add constraint FKb3ba1m83ok6lns3gm5hpw93hw foreign key (fk_Cache_Statut) references Statut (ID_Statut);
alter table Cache add constraint FKruvu6dsuvg2py4iuttwr8k12n foreign key (fk_Cache_Type) references Type (ID_Type);
create table Cache (NUMERO integer not null auto_increment, fk_Cache_Statut integer, fk_Cache_Type integer, descriptionTechnique varchar(100), descriptionTextuelle varchar(100), informationsGeolocalisation varchar(100), rubriqueLibre varchar(100), primary key (NUMERO)) engine=InnoDB;
create table Statut (ID_Statut integer not null auto_increment, Texte varchar(50), primary key (ID_Statut)) engine=InnoDB;
create table Type (ID_Type integer not null auto_increment, Texte varchar(50), primary key (ID_Type)) engine=InnoDB;
alter table Cache add constraint FKb3ba1m83ok6lns3gm5hpw93hw foreign key (fk_Cache_Statut) references Statut (ID_Statut);
alter table Cache add constraint FKruvu6dsuvg2py4iuttwr8k12n foreign key (fk_Cache_Type) references Type (ID_Type);
create table Cache (NUMERO integer not null auto_increment, fk_Cache_Statut integer, fk_Cache_Type integer, descriptionTechnique varchar(100), descriptionTextuelle varchar(100), informationsGeolocalisation varchar(100), rubriqueLibre varchar(100), primary key (NUMERO)) engine=InnoDB;
create table Statut (ID_Statut integer not null auto_increment, Texte varchar(50), primary key (ID_Statut)) engine=InnoDB;
create table Type (ID_Type integer not null auto_increment, Texte varchar(50), primary key (ID_Type)) engine=InnoDB;
alter table Cache add constraint FKb3ba1m83ok6lns3gm5hpw93hw foreign key (fk_Cache_Statut) references Statut (ID_Statut);
alter table Cache add constraint FKruvu6dsuvg2py4iuttwr8k12n foreign key (fk_Cache_Type) references Type (ID_Type);
create table Cache (NUMERO integer not null auto_increment, fk_Cache_Statut integer, fk_Cache_Type integer, descriptionTechnique varchar(100), descriptionTextuelle varchar(100), informationsGeolocalisation varchar(100), rubriqueLibre varchar(100), primary key (NUMERO)) engine=InnoDB;
create table Statut (ID_Statut integer not null auto_increment, Texte varchar(50), primary key (ID_Statut)) engine=InnoDB;
create table Type (ID_Type integer not null auto_increment, Texte varchar(50), primary key (ID_Type)) engine=InnoDB;
alter table Cache add constraint FKb3ba1m83ok6lns3gm5hpw93hw foreign key (fk_Cache_Statut) references Statut (ID_Statut);
alter table Cache add constraint FKruvu6dsuvg2py4iuttwr8k12n foreign key (fk_Cache_Type) references Type (ID_Type);
create table Cache (NUMERO integer not null auto_increment, fk_Cache_Statut integer, fk_Cache_Type integer, descriptionTechnique varchar(100), descriptionTextuelle varchar(100), informationsGeolocalisation varchar(100), rubriqueLibre varchar(100), primary key (NUMERO)) engine=InnoDB;
create table Statut (ID_Statut integer not null auto_increment, Texte varchar(50), primary key (ID_Statut)) engine=InnoDB;
create table Type (ID_Type integer not null auto_increment, Texte varchar(50), primary key (ID_Type)) engine=InnoDB;
alter table Cache add constraint FKb3ba1m83ok6lns3gm5hpw93hw foreign key (fk_Cache_Statut) references Statut (ID_Statut);
alter table Cache add constraint FKruvu6dsuvg2py4iuttwr8k12n foreign key (fk_Cache_Type) references Type (ID_Type);
create table Cache (NUMERO integer not null auto_increment, fk_Cache_Statut integer, fk_Cache_Type integer, descriptionTechnique varchar(100), descriptionTextuelle varchar(100), informationsGeolocalisation varchar(100), rubriqueLibre varchar(100), primary key (NUMERO)) engine=InnoDB;
create table Statut (ID_Statut integer not null auto_increment, Texte varchar(50), primary key (ID_Statut)) engine=InnoDB;
create table Type (ID_Type integer not null auto_increment, Texte varchar(50), primary key (ID_Type)) engine=InnoDB;
alter table Cache add constraint FKb3ba1m83ok6lns3gm5hpw93hw foreign key (fk_Cache_Statut) references Statut (ID_Statut);
alter table Cache add constraint FKruvu6dsuvg2py4iuttwr8k12n foreign key (fk_Cache_Type) references Type (ID_Type);
create table Cache (NUMERO integer not null auto_increment, fk_Cache_Statut integer, fk_Cache_Type integer, fk_ReseauCache_Id integer, descriptionTechnique varchar(100), descriptionTextuelle varchar(100), informationsGeolocalisation varchar(100), rubriqueLibre varchar(100), primary key (NUMERO)) engine=InnoDB;
create table LOG (ID integer not null auto_increment, PROPRIETAIRE_ID integer, fk_Cache_Id integer, note integer not null, trouver bit not null, DATE datetime(6) not null, COMMENTAIRE varchar(255) not null, primary key (ID)) engine=InnoDB;
create table RESEAU_CACHE (ID integer not null auto_increment, PROPRIETAIRE_ID integer, nom varchar(255), primary key (ID)) engine=InnoDB;
create table Statut (ID_Statut integer not null auto_increment, Texte varchar(50), primary key (ID_Statut)) engine=InnoDB;
create table Type (ID_Type integer not null auto_increment, Texte varchar(50), primary key (ID_Type)) engine=InnoDB;
create table UTILISATEUR (ID integer not null auto_increment, admin bit not null, MDP varchar(255) not null, PSEUDO varchar(255) not null, primary key (ID)) engine=InnoDB;
create table UTILISATEUR_RESEAU_CACHE (RESEAU_CACHE_ID integer not null, UTILISATEUR_ID integer not null) engine=InnoDB;
alter table Cache add constraint FKhk671wl1bbgfctdbgyg1gtp45 foreign key (fk_ReseauCache_Id) references RESEAU_CACHE (ID);
alter table Cache add constraint FKb3ba1m83ok6lns3gm5hpw93hw foreign key (fk_Cache_Statut) references Statut (ID_Statut);
alter table Cache add constraint FKruvu6dsuvg2py4iuttwr8k12n foreign key (fk_Cache_Type) references Type (ID_Type);
alter table LOG add constraint FKeyh6k7xvdnnen5f7mjnci1ux0 foreign key (fk_Cache_Id) references Cache (NUMERO);
alter table LOG add constraint FKih76wucwm4uf1hqvxs3dcslya foreign key (PROPRIETAIRE_ID) references UTILISATEUR (ID);
alter table RESEAU_CACHE add constraint FKkw04y08agena8yq1f1b34cdrd foreign key (PROPRIETAIRE_ID) references UTILISATEUR (ID);
alter table UTILISATEUR_RESEAU_CACHE add constraint FK6bnfkl3ogld3u7s6pbjkfoyh9 foreign key (UTILISATEUR_ID) references UTILISATEUR (ID);
alter table UTILISATEUR_RESEAU_CACHE add constraint FKn8v1ymlighjiycw8t873rp2jj foreign key (RESEAU_CACHE_ID) references RESEAU_CACHE (ID);
create table Cache (NUMERO integer not null auto_increment, fk_Cache_Statut integer, fk_Cache_Type integer, fk_ReseauCache_Id integer, descriptionTechnique varchar(100), descriptionTextuelle varchar(100), informationsGeolocalisation varchar(100), rubriqueLibre varchar(100), primary key (NUMERO)) engine=InnoDB;
create table LOG (ID integer not null auto_increment, PROPRIETAIRE_ID integer, fk_Cache_Id integer, note integer not null, trouver bit not null, DATE datetime(6) not null, COMMENTAIRE varchar(255) not null, primary key (ID)) engine=InnoDB;
create table RESEAU_CACHE (ID integer not null auto_increment, PROPRIETAIRE_ID integer, nom varchar(255), primary key (ID)) engine=InnoDB;
create table Statut (ID_Statut integer not null auto_increment, Texte varchar(50), primary key (ID_Statut)) engine=InnoDB;
create table Type (ID_Type integer not null auto_increment, Texte varchar(50), primary key (ID_Type)) engine=InnoDB;
create table UTILISATEUR (ID integer not null auto_increment, admin bit not null, MDP varchar(255) not null, PSEUDO varchar(255) not null, primary key (ID)) engine=InnoDB;
create table UTILISATEUR_RESEAU_CACHE (RESEAU_CACHE_ID integer not null, UTILISATEUR_ID integer not null) engine=InnoDB;
alter table Cache add constraint FKhk671wl1bbgfctdbgyg1gtp45 foreign key (fk_ReseauCache_Id) references RESEAU_CACHE (ID);
alter table Cache add constraint FKb3ba1m83ok6lns3gm5hpw93hw foreign key (fk_Cache_Statut) references Statut (ID_Statut);
alter table Cache add constraint FKruvu6dsuvg2py4iuttwr8k12n foreign key (fk_Cache_Type) references Type (ID_Type);
alter table LOG add constraint FKeyh6k7xvdnnen5f7mjnci1ux0 foreign key (fk_Cache_Id) references Cache (NUMERO);
alter table LOG add constraint FKih76wucwm4uf1hqvxs3dcslya foreign key (PROPRIETAIRE_ID) references UTILISATEUR (ID);
alter table RESEAU_CACHE add constraint FKkw04y08agena8yq1f1b34cdrd foreign key (PROPRIETAIRE_ID) references UTILISATEUR (ID);
alter table UTILISATEUR_RESEAU_CACHE add constraint FK6bnfkl3ogld3u7s6pbjkfoyh9 foreign key (UTILISATEUR_ID) references UTILISATEUR (ID);
alter table UTILISATEUR_RESEAU_CACHE add constraint FKn8v1ymlighjiycw8t873rp2jj foreign key (RESEAU_CACHE_ID) references RESEAU_CACHE (ID);
create table Cache (NUMERO integer not null auto_increment, fk_Cache_Statut integer, fk_Cache_Type integer, fk_ReseauCache_Id integer, informationsGeolocalisation varchar(100), descriptionTechnique varchar(300), descriptionTextuelle varchar(300), rubriqueLibre varchar(300), primary key (NUMERO)) engine=InnoDB;
create table LOG (ID integer not null auto_increment, PROPRIETAIRE_ID integer, fk_Cache_Id integer, note integer not null, trouver bit not null, DATE datetime(6) not null, COMMENTAIRE varchar(255) not null, primary key (ID)) engine=InnoDB;
create table RESEAU_CACHE (ID integer not null auto_increment, PROPRIETAIRE_ID integer, nom varchar(255), primary key (ID)) engine=InnoDB;
create table Statut (ID_Statut integer not null auto_increment, Texte varchar(50), primary key (ID_Statut)) engine=InnoDB;
create table Type (ID_Type integer not null auto_increment, Texte varchar(50), primary key (ID_Type)) engine=InnoDB;
create table UTILISATEUR (ID integer not null auto_increment, admin bit not null, MDP varchar(255) not null, PSEUDO varchar(255) not null, primary key (ID)) engine=InnoDB;
create table UTILISATEUR_RESEAU_CACHE (RESEAU_CACHE_ID integer not null, UTILISATEUR_ID integer not null) engine=InnoDB;
alter table Cache add constraint FKhk671wl1bbgfctdbgyg1gtp45 foreign key (fk_ReseauCache_Id) references RESEAU_CACHE (ID);
alter table Cache add constraint FKb3ba1m83ok6lns3gm5hpw93hw foreign key (fk_Cache_Statut) references Statut (ID_Statut);
alter table Cache add constraint FKruvu6dsuvg2py4iuttwr8k12n foreign key (fk_Cache_Type) references Type (ID_Type);
alter table LOG add constraint FKeyh6k7xvdnnen5f7mjnci1ux0 foreign key (fk_Cache_Id) references Cache (NUMERO);
alter table LOG add constraint FKih76wucwm4uf1hqvxs3dcslya foreign key (PROPRIETAIRE_ID) references UTILISATEUR (ID);
alter table RESEAU_CACHE add constraint FKkw04y08agena8yq1f1b34cdrd foreign key (PROPRIETAIRE_ID) references UTILISATEUR (ID);
alter table UTILISATEUR_RESEAU_CACHE add constraint FK6bnfkl3ogld3u7s6pbjkfoyh9 foreign key (UTILISATEUR_ID) references UTILISATEUR (ID);
alter table UTILISATEUR_RESEAU_CACHE add constraint FKn8v1ymlighjiycw8t873rp2jj foreign key (RESEAU_CACHE_ID) references RESEAU_CACHE (ID);
create table Cache (NUMERO integer not null auto_increment, fk_Cache_Statut integer, fk_Cache_Type integer, fk_ReseauCache_Id integer, informationsGeolocalisation varchar(100), descriptionTechnique varchar(300), descriptionTextuelle varchar(300), rubriqueLibre varchar(300), primary key (NUMERO)) engine=InnoDB;
create table LOG (ID integer not null auto_increment, PROPRIETAIRE_ID integer, fk_Cache_Id integer, note integer not null, trouver bit not null, DATE datetime(6) not null, COMMENTAIRE varchar(255) not null, primary key (ID)) engine=InnoDB;
create table RESEAU_CACHE (ID integer not null auto_increment, PROPRIETAIRE_ID integer, nom varchar(255), primary key (ID)) engine=InnoDB;
create table Statut (ID_Statut integer not null auto_increment, Texte varchar(50), primary key (ID_Statut)) engine=InnoDB;
create table Type (ID_Type integer not null auto_increment, Texte varchar(50), primary key (ID_Type)) engine=InnoDB;
create table UTILISATEUR (ID integer not null auto_increment, admin bit not null, MDP varchar(255) not null, PSEUDO varchar(255) not null, primary key (ID)) engine=InnoDB;
create table UTILISATEUR_RESEAU_CACHE (RESEAU_CACHE_ID integer not null, UTILISATEUR_ID integer not null) engine=InnoDB;
alter table Cache add constraint FKhk671wl1bbgfctdbgyg1gtp45 foreign key (fk_ReseauCache_Id) references RESEAU_CACHE (ID);
alter table Cache add constraint FKb3ba1m83ok6lns3gm5hpw93hw foreign key (fk_Cache_Statut) references Statut (ID_Statut);
alter table Cache add constraint FKruvu6dsuvg2py4iuttwr8k12n foreign key (fk_Cache_Type) references Type (ID_Type);
alter table LOG add constraint FKeyh6k7xvdnnen5f7mjnci1ux0 foreign key (fk_Cache_Id) references Cache (NUMERO);
alter table LOG add constraint FKih76wucwm4uf1hqvxs3dcslya foreign key (PROPRIETAIRE_ID) references UTILISATEUR (ID);
alter table RESEAU_CACHE add constraint FKkw04y08agena8yq1f1b34cdrd foreign key (PROPRIETAIRE_ID) references UTILISATEUR (ID);
alter table UTILISATEUR_RESEAU_CACHE add constraint FK6bnfkl3ogld3u7s6pbjkfoyh9 foreign key (UTILISATEUR_ID) references UTILISATEUR (ID);
alter table UTILISATEUR_RESEAU_CACHE add constraint FKn8v1ymlighjiycw8t873rp2jj foreign key (RESEAU_CACHE_ID) references RESEAU_CACHE (ID);
create table Cache (NUMERO integer not null auto_increment, fk_Cache_Statut integer, fk_Cache_Type integer, fk_ReseauCache_Id integer, informationsGeolocalisation varchar(100), descriptionTechnique varchar(300), descriptionTextuelle varchar(300), rubriqueLibre varchar(300), primary key (NUMERO)) engine=InnoDB;
create table LOG (ID integer not null auto_increment, PROPRIETAIRE_ID integer, fk_Cache_Id integer, note integer not null, trouver bit not null, DATE datetime(6) not null, COMMENTAIRE varchar(255) not null, primary key (ID)) engine=InnoDB;
create table RESEAU_CACHE (ID integer not null auto_increment, PROPRIETAIRE_ID integer, nom varchar(255), primary key (ID)) engine=InnoDB;
create table Statut (ID_Statut integer not null auto_increment, Texte varchar(50), primary key (ID_Statut)) engine=InnoDB;
create table Type (ID_Type integer not null auto_increment, Texte varchar(50), primary key (ID_Type)) engine=InnoDB;
create table UTILISATEUR (ID integer not null auto_increment, admin bit not null, MDP varchar(255) not null, PSEUDO varchar(255) not null, primary key (ID)) engine=InnoDB;
create table UTILISATEUR_RESEAU_CACHE (RESEAU_CACHE_ID integer not null, UTILISATEUR_ID integer not null) engine=InnoDB;
alter table Cache add constraint FKhk671wl1bbgfctdbgyg1gtp45 foreign key (fk_ReseauCache_Id) references RESEAU_CACHE (ID);
alter table Cache add constraint FKb3ba1m83ok6lns3gm5hpw93hw foreign key (fk_Cache_Statut) references Statut (ID_Statut);
alter table Cache add constraint FKruvu6dsuvg2py4iuttwr8k12n foreign key (fk_Cache_Type) references Type (ID_Type);
alter table LOG add constraint FKeyh6k7xvdnnen5f7mjnci1ux0 foreign key (fk_Cache_Id) references Cache (NUMERO);
alter table LOG add constraint FKih76wucwm4uf1hqvxs3dcslya foreign key (PROPRIETAIRE_ID) references UTILISATEUR (ID);
alter table RESEAU_CACHE add constraint FKkw04y08agena8yq1f1b34cdrd foreign key (PROPRIETAIRE_ID) references UTILISATEUR (ID);
alter table UTILISATEUR_RESEAU_CACHE add constraint FK6bnfkl3ogld3u7s6pbjkfoyh9 foreign key (UTILISATEUR_ID) references UTILISATEUR (ID);
alter table UTILISATEUR_RESEAU_CACHE add constraint FKn8v1ymlighjiycw8t873rp2jj foreign key (RESEAU_CACHE_ID) references RESEAU_CACHE (ID);
create table Cache (NUMERO integer not null auto_increment, fk_Cache_Statut integer, fk_Cache_Type integer, fk_ReseauCache_Id integer, informationsGeolocalisation varchar(100), descriptionTechnique varchar(300), descriptionTextuelle varchar(300), rubriqueLibre varchar(300), primary key (NUMERO)) engine=InnoDB;
create table LOG (ID integer not null auto_increment, PROPRIETAIRE_ID integer, fk_Cache_Id integer, note integer not null, trouver bit not null, DATE datetime(6) not null, COMMENTAIRE varchar(255) not null, primary key (ID)) engine=InnoDB;
create table RESEAU_CACHE (ID integer not null auto_increment, PROPRIETAIRE_ID integer, nom varchar(255), primary key (ID)) engine=InnoDB;
create table Statut (ID_Statut integer not null auto_increment, Texte varchar(50), primary key (ID_Statut)) engine=InnoDB;
create table Type (ID_Type integer not null auto_increment, Texte varchar(50), primary key (ID_Type)) engine=InnoDB;
create table UTILISATEUR (ID integer not null auto_increment, admin bit not null, MDP varchar(255) not null, PSEUDO varchar(255) not null, primary key (ID)) engine=InnoDB;
create table UTILISATEUR_RESEAU_CACHE (RESEAU_CACHE_ID integer not null, UTILISATEUR_ID integer not null) engine=InnoDB;
alter table Cache add constraint FKhk671wl1bbgfctdbgyg1gtp45 foreign key (fk_ReseauCache_Id) references RESEAU_CACHE (ID);
alter table Cache add constraint FKb3ba1m83ok6lns3gm5hpw93hw foreign key (fk_Cache_Statut) references Statut (ID_Statut);
alter table Cache add constraint FKruvu6dsuvg2py4iuttwr8k12n foreign key (fk_Cache_Type) references Type (ID_Type);
alter table LOG add constraint FKeyh6k7xvdnnen5f7mjnci1ux0 foreign key (fk_Cache_Id) references Cache (NUMERO);
alter table LOG add constraint FKih76wucwm4uf1hqvxs3dcslya foreign key (PROPRIETAIRE_ID) references UTILISATEUR (ID);
alter table RESEAU_CACHE add constraint FKkw04y08agena8yq1f1b34cdrd foreign key (PROPRIETAIRE_ID) references UTILISATEUR (ID);
alter table UTILISATEUR_RESEAU_CACHE add constraint FK6bnfkl3ogld3u7s6pbjkfoyh9 foreign key (UTILISATEUR_ID) references UTILISATEUR (ID);
alter table UTILISATEUR_RESEAU_CACHE add constraint FKn8v1ymlighjiycw8t873rp2jj foreign key (RESEAU_CACHE_ID) references RESEAU_CACHE (ID);
