create table Cache (ID_Statut integer, ID_Type integer, NUMERO integer not null auto_increment, descriptionTechnique varchar(100), descriptionTextuelle varchar(100), informationsGeolocalisation varchar(100), rubriqueLibre varchar(100), primary key (NUMERO)) engine=InnoDB;
create table Statut (ID_Statut integer not null auto_increment, Texte varchar(50), primary key (ID_Statut)) engine=InnoDB;
create table Type (ID_Type integer not null auto_increment, Texte varchar(50), primary key (ID_Type)) engine=InnoDB;
alter table Cache add constraint UK62xkb7i2a9oy0mq5lvt014x47 unique (ID_Statut);
alter table Cache add constraint UKsuwofma9u4b4t6h3lefqftmq8 unique (ID_Type);
alter table Cache add constraint FK4g92qulrgjbexfylmq5xstfk7 foreign key (ID_Statut) references Statut (ID_Statut);
alter table Cache add constraint FK1ham39cdnqpa86lqysyp43lpm foreign key (ID_Type) references Type (ID_Type);
create table Cache (ID_Statut integer, ID_Type integer, NUMERO integer not null auto_increment, descriptionTechnique varchar(100), descriptionTextuelle varchar(100), informationsGeolocalisation varchar(100), rubriqueLibre varchar(100), primary key (NUMERO)) engine=InnoDB;
create table Statut (ID_Statut integer not null auto_increment, Texte varchar(50), primary key (ID_Statut)) engine=InnoDB;
create table Type (ID_Type integer not null auto_increment, Texte varchar(50), primary key (ID_Type)) engine=InnoDB;
alter table Cache add constraint UK62xkb7i2a9oy0mq5lvt014x47 unique (ID_Statut);
alter table Cache add constraint UKsuwofma9u4b4t6h3lefqftmq8 unique (ID_Type);
alter table Cache add constraint FK4g92qulrgjbexfylmq5xstfk7 foreign key (ID_Statut) references Statut (ID_Statut);
alter table Cache add constraint FK1ham39cdnqpa86lqysyp43lpm foreign key (ID_Type) references Type (ID_Type);
create table Cache (ID_Statut integer, ID_Type integer, NUMERO integer not null auto_increment, descriptionTechnique varchar(100), descriptionTextuelle varchar(100), informationsGeolocalisation varchar(100), rubriqueLibre varchar(100), primary key (NUMERO)) engine=InnoDB;
create table Statut (ID_Statut integer not null auto_increment, Texte varchar(50), primary key (ID_Statut)) engine=InnoDB;
create table Type (ID_Type integer not null auto_increment, Texte varchar(50), primary key (ID_Type)) engine=InnoDB;
alter table Cache add constraint UK62xkb7i2a9oy0mq5lvt014x47 unique (ID_Statut);
alter table Cache add constraint UKsuwofma9u4b4t6h3lefqftmq8 unique (ID_Type);
alter table Cache add constraint FK4g92qulrgjbexfylmq5xstfk7 foreign key (ID_Statut) references Statut (ID_Statut);
alter table Cache add constraint FK1ham39cdnqpa86lqysyp43lpm foreign key (ID_Type) references Type (ID_Type);
create table Cache (ID_Statut integer, ID_Type integer, NUMERO integer not null auto_increment, descriptionTechnique varchar(100), descriptionTextuelle varchar(100), informationsGeolocalisation varchar(100), rubriqueLibre varchar(100), primary key (NUMERO)) engine=InnoDB;
create table Statut (ID_Statut integer not null auto_increment, Texte varchar(50), primary key (ID_Statut)) engine=InnoDB;
create table Type (ID_Type integer not null auto_increment, Texte varchar(50), primary key (ID_Type)) engine=InnoDB;
alter table Cache add constraint UK62xkb7i2a9oy0mq5lvt014x47 unique (ID_Statut);
alter table Cache add constraint UKsuwofma9u4b4t6h3lefqftmq8 unique (ID_Type);
alter table Cache add constraint FK4g92qulrgjbexfylmq5xstfk7 foreign key (ID_Statut) references Statut (ID_Statut);
alter table Cache add constraint FK1ham39cdnqpa86lqysyp43lpm foreign key (ID_Type) references Type (ID_Type);
create table Cache (ID_Statut integer, ID_Type integer, NUMERO integer not null auto_increment, descriptionTechnique varchar(100), descriptionTextuelle varchar(100), informationsGeolocalisation varchar(100), rubriqueLibre varchar(100), primary key (NUMERO)) engine=InnoDB;
create table Statut (ID_Statut integer not null auto_increment, Texte varchar(50), primary key (ID_Statut)) engine=InnoDB;
create table Type (ID_Type integer not null auto_increment, Texte varchar(50), primary key (ID_Type)) engine=InnoDB;
alter table Cache add constraint UK62xkb7i2a9oy0mq5lvt014x47 unique (ID_Statut);
alter table Cache add constraint UKsuwofma9u4b4t6h3lefqftmq8 unique (ID_Type);
alter table Cache add constraint FK4g92qulrgjbexfylmq5xstfk7 foreign key (ID_Statut) references Statut (ID_Statut);
alter table Cache add constraint FK1ham39cdnqpa86lqysyp43lpm foreign key (ID_Type) references Type (ID_Type);
create table Cache (ID_Statut integer, ID_Type integer, NUMERO integer not null auto_increment, descriptionTechnique varchar(100), descriptionTextuelle varchar(100), informationsGeolocalisation varchar(100), rubriqueLibre varchar(100), primary key (NUMERO)) engine=InnoDB;
create table Statut (ID_Statut integer not null auto_increment, Texte varchar(50), primary key (ID_Statut)) engine=InnoDB;
create table Type (ID_Type integer not null auto_increment, Texte varchar(50), primary key (ID_Type)) engine=InnoDB;
alter table Cache add constraint UK62xkb7i2a9oy0mq5lvt014x47 unique (ID_Statut);
alter table Cache add constraint UKsuwofma9u4b4t6h3lefqftmq8 unique (ID_Type);
alter table Cache add constraint FK4g92qulrgjbexfylmq5xstfk7 foreign key (ID_Statut) references Statut (ID_Statut);
alter table Cache add constraint FK1ham39cdnqpa86lqysyp43lpm foreign key (ID_Type) references Type (ID_Type);
create table Cache (ID_Statut integer, ID_Type integer, NUMERO integer not null auto_increment, descriptionTechnique varchar(100), descriptionTextuelle varchar(100), informationsGeolocalisation varchar(100), rubriqueLibre varchar(100), primary key (NUMERO)) engine=InnoDB;
create table Statut (ID_Statut integer not null auto_increment, Texte varchar(50), primary key (ID_Statut)) engine=InnoDB;
create table Type (ID_Type integer not null auto_increment, Texte varchar(50), primary key (ID_Type)) engine=InnoDB;
alter table Cache add constraint UK62xkb7i2a9oy0mq5lvt014x47 unique (ID_Statut);
alter table Cache add constraint UKsuwofma9u4b4t6h3lefqftmq8 unique (ID_Type);
alter table Cache add constraint FK4g92qulrgjbexfylmq5xstfk7 foreign key (ID_Statut) references Statut (ID_Statut);
alter table Cache add constraint FK1ham39cdnqpa86lqysyp43lpm foreign key (ID_Type) references Type (ID_Type);
create table Cache (ID_Statut integer, ID_Type integer, NUMERO integer not null auto_increment, descriptionTechnique varchar(100), descriptionTextuelle varchar(100), informationsGeolocalisation varchar(100), rubriqueLibre varchar(100), primary key (NUMERO)) engine=InnoDB;
create table Statut (ID_Statut integer not null auto_increment, Texte varchar(50), primary key (ID_Statut)) engine=InnoDB;
create table Type (ID_Type integer not null auto_increment, Texte varchar(50), primary key (ID_Type)) engine=InnoDB;
alter table Cache add constraint UK62xkb7i2a9oy0mq5lvt014x47 unique (ID_Statut);
alter table Cache add constraint UKsuwofma9u4b4t6h3lefqftmq8 unique (ID_Type);
alter table Cache add constraint FK4g92qulrgjbexfylmq5xstfk7 foreign key (ID_Statut) references Statut (ID_Statut);
alter table Cache add constraint FK1ham39cdnqpa86lqysyp43lpm foreign key (ID_Type) references Type (ID_Type);
