alter table Cache drop foreign key FK4g92qulrgjbexfylmq5xstfk7;
alter table Cache drop foreign key FK1ham39cdnqpa86lqysyp43lpm;
drop table if exists Cache;
drop table if exists Statut;
drop table if exists Type;
alter table Cache drop foreign key FK4g92qulrgjbexfylmq5xstfk7;
alter table Cache drop foreign key FK1ham39cdnqpa86lqysyp43lpm;
drop table if exists Cache;
drop table if exists Statut;
drop table if exists Type;
alter table Cache drop foreign key FK4g92qulrgjbexfylmq5xstfk7;
alter table Cache drop foreign key FK1ham39cdnqpa86lqysyp43lpm;
drop table if exists Cache;
drop table if exists Statut;
drop table if exists Type;
alter table Cache drop foreign key FK4g92qulrgjbexfylmq5xstfk7;
alter table Cache drop foreign key FK1ham39cdnqpa86lqysyp43lpm;
drop table if exists Cache;
drop table if exists Statut;
drop table if exists Type;
alter table Cache drop foreign key FK4g92qulrgjbexfylmq5xstfk7;
alter table Cache drop foreign key FK1ham39cdnqpa86lqysyp43lpm;
drop table if exists Cache;
drop table if exists Statut;
drop table if exists Type;
alter table Cache drop foreign key FK4g92qulrgjbexfylmq5xstfk7;
alter table Cache drop foreign key FK1ham39cdnqpa86lqysyp43lpm;
drop table if exists Cache;
drop table if exists Statut;
drop table if exists Type;
alter table Cache drop foreign key FK4g92qulrgjbexfylmq5xstfk7;
alter table Cache drop foreign key FK1ham39cdnqpa86lqysyp43lpm;
drop table if exists Cache;
drop table if exists Statut;
drop table if exists Type;
alter table Cache drop foreign key FK4g92qulrgjbexfylmq5xstfk7;
alter table Cache drop foreign key FK1ham39cdnqpa86lqysyp43lpm;
drop table if exists Cache;
drop table if exists Statut;
drop table if exists Type;
alter table Cache drop foreign key FKb3ba1m83ok6lns3gm5hpw93hw;
alter table Cache drop foreign key FKruvu6dsuvg2py4iuttwr8k12n;
drop table if exists Cache;
drop table if exists Statut;
drop table if exists Type;
alter table Cache drop foreign key FKb3ba1m83ok6lns3gm5hpw93hw;
alter table Cache drop foreign key FKruvu6dsuvg2py4iuttwr8k12n;
drop table if exists Cache;
drop table if exists Statut;
drop table if exists Type;
alter table Cache drop foreign key FKb3ba1m83ok6lns3gm5hpw93hw;
alter table Cache drop foreign key FKruvu6dsuvg2py4iuttwr8k12n;
drop table if exists Cache;
drop table if exists Statut;
drop table if exists Type;
alter table Cache drop foreign key FKb3ba1m83ok6lns3gm5hpw93hw;
alter table Cache drop foreign key FKruvu6dsuvg2py4iuttwr8k12n;
drop table if exists Cache;
drop table if exists Statut;
drop table if exists Type;
alter table Cache drop foreign key FKb3ba1m83ok6lns3gm5hpw93hw;
alter table Cache drop foreign key FKruvu6dsuvg2py4iuttwr8k12n;
drop table if exists Cache;
drop table if exists Statut;
drop table if exists Type;
alter table Cache drop foreign key FKb3ba1m83ok6lns3gm5hpw93hw;
alter table Cache drop foreign key FKruvu6dsuvg2py4iuttwr8k12n;
drop table if exists Cache;
drop table if exists Statut;
drop table if exists Type;
alter table Cache drop foreign key FKb3ba1m83ok6lns3gm5hpw93hw;
alter table Cache drop foreign key FKruvu6dsuvg2py4iuttwr8k12n;
drop table if exists Cache;
drop table if exists Statut;
drop table if exists Type;
alter table Cache drop foreign key FKb3ba1m83ok6lns3gm5hpw93hw;
alter table Cache drop foreign key FKruvu6dsuvg2py4iuttwr8k12n;
drop table if exists Cache;
drop table if exists Statut;
drop table if exists Type;
alter table Cache drop foreign key FKb3ba1m83ok6lns3gm5hpw93hw;
alter table Cache drop foreign key FKruvu6dsuvg2py4iuttwr8k12n;
drop table if exists Cache;
drop table if exists Statut;
drop table if exists Type;
alter table Cache drop foreign key FKb3ba1m83ok6lns3gm5hpw93hw;
alter table Cache drop foreign key FKruvu6dsuvg2py4iuttwr8k12n;
drop table if exists Cache;
drop table if exists Statut;
drop table if exists Type;
alter table Cache drop foreign key FKb3ba1m83ok6lns3gm5hpw93hw;
alter table Cache drop foreign key FKruvu6dsuvg2py4iuttwr8k12n;
drop table if exists Cache;
drop table if exists Statut;
drop table if exists Type;
alter table Cache drop foreign key FKb3ba1m83ok6lns3gm5hpw93hw;
alter table Cache drop foreign key FKruvu6dsuvg2py4iuttwr8k12n;
drop table if exists Cache;
drop table if exists Statut;
drop table if exists Type;
alter table Cache drop foreign key FKhk671wl1bbgfctdbgyg1gtp45;
alter table Cache drop foreign key FKb3ba1m83ok6lns3gm5hpw93hw;
alter table Cache drop foreign key FKruvu6dsuvg2py4iuttwr8k12n;
alter table LOG drop foreign key FKeyh6k7xvdnnen5f7mjnci1ux0;
alter table LOG drop foreign key FKih76wucwm4uf1hqvxs3dcslya;
alter table RESEAU_CACHE drop foreign key FKkw04y08agena8yq1f1b34cdrd;
alter table UTILISATEUR_RESEAU_CACHE drop foreign key FK6bnfkl3ogld3u7s6pbjkfoyh9;
alter table UTILISATEUR_RESEAU_CACHE drop foreign key FKn8v1ymlighjiycw8t873rp2jj;
drop table if exists Cache;
drop table if exists LOG;
drop table if exists RESEAU_CACHE;
drop table if exists Statut;
drop table if exists Type;
drop table if exists UTILISATEUR;
drop table if exists UTILISATEUR_RESEAU_CACHE;
alter table Cache drop foreign key FKhk671wl1bbgfctdbgyg1gtp45;
alter table Cache drop foreign key FKb3ba1m83ok6lns3gm5hpw93hw;
alter table Cache drop foreign key FKruvu6dsuvg2py4iuttwr8k12n;
alter table LOG drop foreign key FKeyh6k7xvdnnen5f7mjnci1ux0;
alter table LOG drop foreign key FKih76wucwm4uf1hqvxs3dcslya;
alter table RESEAU_CACHE drop foreign key FKkw04y08agena8yq1f1b34cdrd;
alter table UTILISATEUR_RESEAU_CACHE drop foreign key FK6bnfkl3ogld3u7s6pbjkfoyh9;
alter table UTILISATEUR_RESEAU_CACHE drop foreign key FKn8v1ymlighjiycw8t873rp2jj;
drop table if exists Cache;
drop table if exists LOG;
drop table if exists RESEAU_CACHE;
drop table if exists Statut;
drop table if exists Type;
drop table if exists UTILISATEUR;
drop table if exists UTILISATEUR_RESEAU_CACHE;
alter table Cache drop foreign key FKhk671wl1bbgfctdbgyg1gtp45;
alter table Cache drop foreign key FKb3ba1m83ok6lns3gm5hpw93hw;
alter table Cache drop foreign key FKruvu6dsuvg2py4iuttwr8k12n;
alter table LOG drop foreign key FKeyh6k7xvdnnen5f7mjnci1ux0;
alter table LOG drop foreign key FKih76wucwm4uf1hqvxs3dcslya;
alter table RESEAU_CACHE drop foreign key FKkw04y08agena8yq1f1b34cdrd;
alter table UTILISATEUR_RESEAU_CACHE drop foreign key FK6bnfkl3ogld3u7s6pbjkfoyh9;
alter table UTILISATEUR_RESEAU_CACHE drop foreign key FKn8v1ymlighjiycw8t873rp2jj;
drop table if exists Cache;
drop table if exists LOG;
drop table if exists RESEAU_CACHE;
drop table if exists Statut;
drop table if exists Type;
drop table if exists UTILISATEUR;
drop table if exists UTILISATEUR_RESEAU_CACHE;
alter table Cache drop foreign key FKhk671wl1bbgfctdbgyg1gtp45;
alter table Cache drop foreign key FKb3ba1m83ok6lns3gm5hpw93hw;
alter table Cache drop foreign key FKruvu6dsuvg2py4iuttwr8k12n;
alter table LOG drop foreign key FKeyh6k7xvdnnen5f7mjnci1ux0;
alter table LOG drop foreign key FKih76wucwm4uf1hqvxs3dcslya;
alter table RESEAU_CACHE drop foreign key FKkw04y08agena8yq1f1b34cdrd;
alter table UTILISATEUR_RESEAU_CACHE drop foreign key FK6bnfkl3ogld3u7s6pbjkfoyh9;
alter table UTILISATEUR_RESEAU_CACHE drop foreign key FKn8v1ymlighjiycw8t873rp2jj;
drop table if exists Cache;
drop table if exists LOG;
drop table if exists RESEAU_CACHE;
drop table if exists Statut;
drop table if exists Type;
drop table if exists UTILISATEUR;
drop table if exists UTILISATEUR_RESEAU_CACHE;
alter table Cache drop foreign key FKhk671wl1bbgfctdbgyg1gtp45;
alter table Cache drop foreign key FKb3ba1m83ok6lns3gm5hpw93hw;
alter table Cache drop foreign key FKruvu6dsuvg2py4iuttwr8k12n;
alter table LOG drop foreign key FKeyh6k7xvdnnen5f7mjnci1ux0;
alter table LOG drop foreign key FKih76wucwm4uf1hqvxs3dcslya;
alter table RESEAU_CACHE drop foreign key FKkw04y08agena8yq1f1b34cdrd;
alter table UTILISATEUR_RESEAU_CACHE drop foreign key FK6bnfkl3ogld3u7s6pbjkfoyh9;
alter table UTILISATEUR_RESEAU_CACHE drop foreign key FKn8v1ymlighjiycw8t873rp2jj;
drop table if exists Cache;
drop table if exists LOG;
drop table if exists RESEAU_CACHE;
drop table if exists Statut;
drop table if exists Type;
drop table if exists UTILISATEUR;
drop table if exists UTILISATEUR_RESEAU_CACHE;
alter table Cache drop foreign key FKhk671wl1bbgfctdbgyg1gtp45;
alter table Cache drop foreign key FKb3ba1m83ok6lns3gm5hpw93hw;
alter table Cache drop foreign key FKruvu6dsuvg2py4iuttwr8k12n;
alter table LOG drop foreign key FKeyh6k7xvdnnen5f7mjnci1ux0;
alter table LOG drop foreign key FKih76wucwm4uf1hqvxs3dcslya;
alter table RESEAU_CACHE drop foreign key FKkw04y08agena8yq1f1b34cdrd;
alter table UTILISATEUR_RESEAU_CACHE drop foreign key FK6bnfkl3ogld3u7s6pbjkfoyh9;
alter table UTILISATEUR_RESEAU_CACHE drop foreign key FKn8v1ymlighjiycw8t873rp2jj;
drop table if exists Cache;
drop table if exists LOG;
drop table if exists RESEAU_CACHE;
drop table if exists Statut;
drop table if exists Type;
drop table if exists UTILISATEUR;
drop table if exists UTILISATEUR_RESEAU_CACHE;
