alter table Cache drop foreign key FK4g92qulrgjbexfylmq5xstfk7;
alter table Cache drop foreign key FK1ham39cdnqpa86lqysyp43lpm;
drop table if exists Cache;
drop table if exists Statut;
drop table if exists Type;
alter table Cache drop foreign key FK4g92qulrgjbexfylmq5xstfk7;
alter table Cache drop foreign key FK1ham39cdnqpa86lqysyp43lpm;
drop table if exists Cache;
drop table if exists Statut;
drop table if exists Type;
alter table Cache drop foreign key FK4g92qulrgjbexfylmq5xstfk7;
alter table Cache drop foreign key FK1ham39cdnqpa86lqysyp43lpm;
drop table if exists Cache;
drop table if exists Statut;
drop table if exists Type;
alter table Cache drop foreign key FK4g92qulrgjbexfylmq5xstfk7;
alter table Cache drop foreign key FK1ham39cdnqpa86lqysyp43lpm;
drop table if exists Cache;
drop table if exists Statut;
drop table if exists Type;
alter table Cache drop foreign key FK4g92qulrgjbexfylmq5xstfk7;
alter table Cache drop foreign key FK1ham39cdnqpa86lqysyp43lpm;
drop table if exists Cache;
drop table if exists Statut;
drop table if exists Type;
alter table Cache drop foreign key FK4g92qulrgjbexfylmq5xstfk7;
alter table Cache drop foreign key FK1ham39cdnqpa86lqysyp43lpm;
drop table if exists Cache;
drop table if exists Statut;
drop table if exists Type;
alter table Cache drop foreign key FK4g92qulrgjbexfylmq5xstfk7;
alter table Cache drop foreign key FK1ham39cdnqpa86lqysyp43lpm;
drop table if exists Cache;
drop table if exists Statut;
drop table if exists Type;
alter table Cache drop foreign key FK4g92qulrgjbexfylmq5xstfk7;
alter table Cache drop foreign key FK1ham39cdnqpa86lqysyp43lpm;
drop table if exists Cache;
drop table if exists Statut;
drop table if exists Type;
