alter table Cache drop foreign key FK4g92qulrgjbexfylmq5xstfk7;
alter table Cache drop foreign key FK1ham39cdnqpa86lqysyp43lpm;
drop table if exists Cache;
drop table if exists Statut;
drop table if exists Type;
alter table Cache drop foreign key FK4g92qulrgjbexfylmq5xstfk7;
alter table Cache drop foreign key FK1ham39cdnqpa86lqysyp43lpm;
drop table if exists Cache;
drop table if exists Statut;
drop table if exists Type;
alter table Cache drop foreign key FK4g92qulrgjbexfylmq5xstfk7;
alter table Cache drop foreign key FK1ham39cdnqpa86lqysyp43lpm;
drop table if exists Cache;
drop table if exists Statut;
drop table if exists Type;
alter table Cache drop foreign key FK4g92qulrgjbexfylmq5xstfk7;
alter table Cache drop foreign key FK1ham39cdnqpa86lqysyp43lpm;
drop table if exists Cache;
drop table if exists Statut;
drop table if exists Type;
alter table Cache drop foreign key FK4g92qulrgjbexfylmq5xstfk7;
alter table Cache drop foreign key FK1ham39cdnqpa86lqysyp43lpm;
drop table if exists Cache;
drop table if exists Statut;
drop table if exists Type;
alter table Cache drop foreign key FK4g92qulrgjbexfylmq5xstfk7;
alter table Cache drop foreign key FK1ham39cdnqpa86lqysyp43lpm;
drop table if exists Cache;
drop table if exists Statut;
drop table if exists Type;
alter table Cache drop foreign key FK4g92qulrgjbexfylmq5xstfk7;
alter table Cache drop foreign key FK1ham39cdnqpa86lqysyp43lpm;
drop table if exists Cache;
drop table if exists Statut;
drop table if exists Type;
alter table Cache drop foreign key FK4g92qulrgjbexfylmq5xstfk7;
alter table Cache drop foreign key FK1ham39cdnqpa86lqysyp43lpm;
drop table if exists Cache;
drop table if exists Statut;
drop table if exists Type;
alter table Cache drop foreign key FKb3ba1m83ok6lns3gm5hpw93hw;
alter table Cache drop foreign key FKruvu6dsuvg2py4iuttwr8k12n;
drop table if exists Cache;
drop table if exists Statut;
drop table if exists Type;
alter table Cache drop foreign key FKb3ba1m83ok6lns3gm5hpw93hw;
alter table Cache drop foreign key FKruvu6dsuvg2py4iuttwr8k12n;
drop table if exists Cache;
drop table if exists Statut;
drop table if exists Type;
alter table Cache drop foreign key FKb3ba1m83ok6lns3gm5hpw93hw;
alter table Cache drop foreign key FKruvu6dsuvg2py4iuttwr8k12n;
drop table if exists Cache;
drop table if exists Statut;
drop table if exists Type;
alter table Cache drop foreign key FKb3ba1m83ok6lns3gm5hpw93hw;
alter table Cache drop foreign key FKruvu6dsuvg2py4iuttwr8k12n;
drop table if exists Cache;
drop table if exists Statut;
drop table if exists Type;
alter table Cache drop foreign key FKb3ba1m83ok6lns3gm5hpw93hw;
alter table Cache drop foreign key FKruvu6dsuvg2py4iuttwr8k12n;
drop table if exists Cache;
drop table if exists Statut;
drop table if exists Type;
alter table Cache drop foreign key FKb3ba1m83ok6lns3gm5hpw93hw;
alter table Cache drop foreign key FKruvu6dsuvg2py4iuttwr8k12n;
drop table if exists Cache;
drop table if exists Statut;
drop table if exists Type;
alter table Cache drop foreign key FKb3ba1m83ok6lns3gm5hpw93hw;
alter table Cache drop foreign key FKruvu6dsuvg2py4iuttwr8k12n;
drop table if exists Cache;
drop table if exists Statut;
drop table if exists Type;
alter table Cache drop foreign key FKb3ba1m83ok6lns3gm5hpw93hw;
alter table Cache drop foreign key FKruvu6dsuvg2py4iuttwr8k12n;
drop table if exists Cache;
drop table if exists Statut;
drop table if exists Type;
alter table Cache drop foreign key FKb3ba1m83ok6lns3gm5hpw93hw;
alter table Cache drop foreign key FKruvu6dsuvg2py4iuttwr8k12n;
drop table if exists Cache;
drop table if exists Statut;
drop table if exists Type;
alter table Cache drop foreign key FKb3ba1m83ok6lns3gm5hpw93hw;
alter table Cache drop foreign key FKruvu6dsuvg2py4iuttwr8k12n;
drop table if exists Cache;
drop table if exists Statut;
drop table if exists Type;
alter table Cache drop foreign key FKb3ba1m83ok6lns3gm5hpw93hw;
alter table Cache drop foreign key FKruvu6dsuvg2py4iuttwr8k12n;
drop table if exists Cache;
drop table if exists Statut;
drop table if exists Type;
alter table Cache drop foreign key FKb3ba1m83ok6lns3gm5hpw93hw;
alter table Cache drop foreign key FKruvu6dsuvg2py4iuttwr8k12n;
drop table if exists Cache;
drop table if exists Statut;
drop table if exists Type;
