drop table if exists UTILISATEUR;
drop table if exists UTILISATEUR;
drop table if exists UTILISATEUR;
drop table if exists UTILISATEUR;
drop table if exists UTILISATEUR;
drop table if exists UTILISATEUR;
drop table if exists UTILISATEUR;
drop table if exists UTILISATEUR;
drop table if exists UTILISATEUR;
drop table if exists UTILISATEUR;
drop table if exists UTILISATEUR;
drop table if exists UTILISATEUR;
drop table if exists UTILISATEUR;
drop table if exists UTILISATEUR;
drop table if exists UTILISATEUR;
drop table if exists UTILISATEUR;
drop table if exists UTILISATEUR;
drop table if exists UTILISATEUR;
drop table if exists UTILISATEUR;
drop table if exists UTILISATEUR;
drop table if exists UTILISATEUR;
drop table if exists UTILISATEUR;
drop table if exists UTILISATEUR;
drop table if exists LOG;
drop table if exists UTILISATEUR;
drop table if exists LOG;
drop table if exists UTILISATEUR;
drop table if exists LOG;
drop table if exists RESEAU_CACHE;
drop table if exists UTILISATEUR;
alter table UTILISATEUR_RESEAU_CACHE drop foreign key FKi0wpf7911vvxd52bvuusrqm2t;
alter table UTILISATEUR_RESEAU_CACHE drop foreign key FK15agwdjrso48n8gk3mnhca8r1;
drop table if exists LOG;
drop table if exists RESEAU_CACHE;
drop table if exists UTILISATEUR;
drop table if exists UTILISATEUR_RESEAU_CACHE;
alter table UTILISATEUR_RESEAU_CACHE drop foreign key FKn8v1ymlighjiycw8t873rp2jj;
alter table UTILISATEUR_RESEAU_CACHE drop foreign key FK6bnfkl3ogld3u7s6pbjkfoyh9;
drop table if exists LOG;
drop table if exists RESEAU_CACHE;
drop table if exists UTILISATEUR;
drop table if exists UTILISATEUR_RESEAU_CACHE;
alter table UTILISATEUR_RESEAU_CACHE drop foreign key FKn8v1ymlighjiycw8t873rp2jj;
alter table UTILISATEUR_RESEAU_CACHE drop foreign key FK6bnfkl3ogld3u7s6pbjkfoyh9;
drop table if exists LOG;
drop table if exists RESEAU_CACHE;
drop table if exists UTILISATEUR;
drop table if exists UTILISATEUR_RESEAU_CACHE;
alter table UTILISATEUR_RESEAU_CACHE drop foreign key FK6bnfkl3ogld3u7s6pbjkfoyh9;
alter table UTILISATEUR_RESEAU_CACHE drop foreign key FKn8v1ymlighjiycw8t873rp2jj;
drop table if exists LOG;
drop table if exists RESEAU_CACHE;
drop table if exists UTILISATEUR;
drop table if exists UTILISATEUR_RESEAU_CACHE;
alter table UTILISATEUR_RESEAU_CACHE drop foreign key FK6bnfkl3ogld3u7s6pbjkfoyh9;
alter table UTILISATEUR_RESEAU_CACHE drop foreign key FKn8v1ymlighjiycw8t873rp2jj;
drop table if exists LOG;
drop table if exists RESEAU_CACHE;
drop table if exists UTILISATEUR;
drop table if exists UTILISATEUR_RESEAU_CACHE;
alter table UTILISATEUR_RESEAU_CACHE drop foreign key FK6bnfkl3ogld3u7s6pbjkfoyh9;
alter table UTILISATEUR_RESEAU_CACHE drop foreign key FKn8v1ymlighjiycw8t873rp2jj;
drop table if exists LOG;
drop table if exists RESEAU_CACHE;
drop table if exists UTILISATEUR;
drop table if exists UTILISATEUR_RESEAU_CACHE;
alter table UTILISATEUR_RESEAU_CACHE drop foreign key FK6bnfkl3ogld3u7s6pbjkfoyh9;
alter table UTILISATEUR_RESEAU_CACHE drop foreign key FKn8v1ymlighjiycw8t873rp2jj;
drop table if exists LOG;
drop table if exists RESEAU_CACHE;
drop table if exists UTILISATEUR;
drop table if exists UTILISATEUR_RESEAU_CACHE;
alter table UTILISATEUR_RESEAU_CACHE drop foreign key FK6bnfkl3ogld3u7s6pbjkfoyh9;
alter table UTILISATEUR_RESEAU_CACHE drop foreign key FKn8v1ymlighjiycw8t873rp2jj;
drop table if exists LOG;
drop table if exists RESEAU_CACHE;
drop table if exists UTILISATEUR;
drop table if exists UTILISATEUR_RESEAU_CACHE;
alter table UTILISATEUR_RESEAU_CACHE drop foreign key FK6bnfkl3ogld3u7s6pbjkfoyh9;
alter table UTILISATEUR_RESEAU_CACHE drop foreign key FKn8v1ymlighjiycw8t873rp2jj;
drop table if exists LOG;
drop table if exists RESEAU_CACHE;
drop table if exists UTILISATEUR;
drop table if exists UTILISATEUR_RESEAU_CACHE;
alter table UTILISATEUR_RESEAU_CACHE drop foreign key FK6bnfkl3ogld3u7s6pbjkfoyh9;
alter table UTILISATEUR_RESEAU_CACHE drop foreign key FKn8v1ymlighjiycw8t873rp2jj;
drop table if exists LOG;
drop table if exists RESEAU_CACHE;
drop table if exists UTILISATEUR;
drop table if exists UTILISATEUR_RESEAU_CACHE;
alter table UTILISATEUR_RESEAU_CACHE drop foreign key FK6bnfkl3ogld3u7s6pbjkfoyh9;
alter table UTILISATEUR_RESEAU_CACHE drop foreign key FKn8v1ymlighjiycw8t873rp2jj;
drop table if exists LOG;
drop table if exists RESEAU_CACHE;
drop table if exists UTILISATEUR;
drop table if exists UTILISATEUR_RESEAU_CACHE;
alter table UTILISATEUR_RESEAU_CACHE drop foreign key FK6bnfkl3ogld3u7s6pbjkfoyh9;
alter table UTILISATEUR_RESEAU_CACHE drop foreign key FKn8v1ymlighjiycw8t873rp2jj;
drop table if exists LOG;
drop table if exists RESEAU_CACHE;
drop table if exists UTILISATEUR;
drop table if exists UTILISATEUR_RESEAU_CACHE;
alter table UTILISATEUR_RESEAU_CACHE drop foreign key FK6bnfkl3ogld3u7s6pbjkfoyh9;
alter table UTILISATEUR_RESEAU_CACHE drop foreign key FKn8v1ymlighjiycw8t873rp2jj;
drop table if exists LOG;
drop table if exists RESEAU_CACHE;
drop table if exists UTILISATEUR;
drop table if exists UTILISATEUR_RESEAU_CACHE;
alter table UTILISATEUR_RESEAU_CACHE drop foreign key FK6bnfkl3ogld3u7s6pbjkfoyh9;
alter table UTILISATEUR_RESEAU_CACHE drop foreign key FKn8v1ymlighjiycw8t873rp2jj;
drop table if exists LOG;
drop table if exists RESEAU_CACHE;
drop table if exists UTILISATEUR;
drop table if exists UTILISATEUR_RESEAU_CACHE;
alter table RESEAU_CACHE drop foreign key FKkw04y08agena8yq1f1b34cdrd;
alter table UTILISATEUR_RESEAU_CACHE drop foreign key FK6bnfkl3ogld3u7s6pbjkfoyh9;
alter table UTILISATEUR_RESEAU_CACHE drop foreign key FKn8v1ymlighjiycw8t873rp2jj;
drop table if exists LOG;
drop table if exists RESEAU_CACHE;
drop table if exists UTILISATEUR;
drop table if exists UTILISATEUR_RESEAU_CACHE;
alter table RESEAU_CACHE drop foreign key FKkw04y08agena8yq1f1b34cdrd;
alter table UTILISATEUR_RESEAU_CACHE drop foreign key FK6bnfkl3ogld3u7s6pbjkfoyh9;
alter table UTILISATEUR_RESEAU_CACHE drop foreign key FKn8v1ymlighjiycw8t873rp2jj;
drop table if exists LOG;
drop table if exists RESEAU_CACHE;
drop table if exists UTILISATEUR;
drop table if exists UTILISATEUR_RESEAU_CACHE;
alter table RESEAU_CACHE drop foreign key FKkw04y08agena8yq1f1b34cdrd;
alter table UTILISATEUR_RESEAU_CACHE drop foreign key FK6bnfkl3ogld3u7s6pbjkfoyh9;
alter table UTILISATEUR_RESEAU_CACHE drop foreign key FKn8v1ymlighjiycw8t873rp2jj;
drop table if exists LOG;
drop table if exists RESEAU_CACHE;
drop table if exists UTILISATEUR;
drop table if exists UTILISATEUR_RESEAU_CACHE;
alter table RESEAU_CACHE drop foreign key FKkw04y08agena8yq1f1b34cdrd;
alter table UTILISATEUR_RESEAU_CACHE drop foreign key FK6bnfkl3ogld3u7s6pbjkfoyh9;
alter table UTILISATEUR_RESEAU_CACHE drop foreign key FKn8v1ymlighjiycw8t873rp2jj;
drop table if exists LOG;
drop table if exists RESEAU_CACHE;
drop table if exists UTILISATEUR;
drop table if exists UTILISATEUR_RESEAU_CACHE;
alter table LOG drop foreign key FKih76wucwm4uf1hqvxs3dcslya;
alter table RESEAU_CACHE drop foreign key FKkw04y08agena8yq1f1b34cdrd;
alter table UTILISATEUR_RESEAU_CACHE drop foreign key FK6bnfkl3ogld3u7s6pbjkfoyh9;
alter table UTILISATEUR_RESEAU_CACHE drop foreign key FKn8v1ymlighjiycw8t873rp2jj;
drop table if exists LOG;
drop table if exists RESEAU_CACHE;
drop table if exists UTILISATEUR;
drop table if exists UTILISATEUR_RESEAU_CACHE;
