@startuml

package "modele" #EEEEEE{

class Utilisateur{
  - id : int
  - pseudo : String 
  - mdp : String
  - admin : bool
  - reseaux : List<ReseauCache>
}

class ReseauCache{
  - listeCaches : List<Cache>
  - idProprietaire : int
  - nom : String
}

class Cache{
  - numero : int
  - descriptionTextuelle : String
  - descriptionTechnique : String 
  - rubriqueLibre : String
  - type : TypeCache
  - listLogs : List<Log>
}

enum TypeCache{
  - id : int 
  - texte : String
}

class Log{
  - id : int
  - commentaire : String
  - trouver : bool
  - note : int
  - date : DateTime
  - image : url /optionnel/
}

Cache --> TypeCache

Utilisateur::reseaux "0..*" -- "0..*" ReseauCache : accède
Utilisateur::id "0..*" -- "1" ReseauCache::idProprietaire : possède

ReseauCache::listCaches "0..*" -- "1" Cache : appartient

Log "1" -- "0..*" Cache : enregister
}

@enduml
