@startuml



package "vue" #EEEEEE{

package "dropdown" #EEEEEE{
class ComboBoxGeneral{
  - cl : CardLayout
  - mainPanel : JPanel
  - requeteGeOOCache : RequeteGeOOCache
  - user : Utilisateur
  - selectionDropdown : selectionDropdown
  - modifVue : int
  - comboBoxAction : JComboBox<String>
  - comboBoxReseauCache : JComboBox<Object>
  - comboBoxCache : JComboBox<Object>
  - comboBoxUtilisateur : JComboBox<Object>
  - comboBoxLog : JComboBox<Object>

  + JComboBox<String> getComboBoxAction()
  + JComboBox<Object> getComboBoxUtilisateur()
  + JComboBox<Object> getComboBoxReseauCache()
  + JComboBox<Object> getComboBoxLog()
  + DefaultComboBoxModel<Object> getDefaultComboBoxModelCache()
  + void refresh()
  + void refreshDataView()
  + void refreshComboBoxUtilisateur()
  + void refreshComboBoxReseau()
  + void refreshComboBoxAction()
  + void refreshComboBoxLog()
  + void refreshComboBoxCache()
}
}

package "page" #EEEEEE{
class Accueil{
  - fenetrePrincipal : FenetrePrincipal
  - sel : SelectionDropdown
  - cl : CardLayout
  - mainPanel : JPanel
  - cb : ComboBoxGeneral

  + JPanel createButtonDeconnexion()
  + JPanel createButtonNav()
  + void refreshDataView()
}

class AssociateUser{
  - utilisateurConnecte : Utilisateur
  - requeteGeOOCache : RequeteGeOOCache
  - comboBoxUtilisateur : JComboBox<Utilisateur>
  - comboBoxReseau : JComboBox<Object>
  - selectionDropdown : SelectionDropdown 
  - comboBoxGeneral : ComboBoxGeneral
  - reussite : JLabel
  - echec : JLabel
  - utilisateur : Utilisateur

  + DefaultComboBoxModel<Object> getDefaultComboBoxModelReseau()
  + JComboBox<Utilisateur> getComboBoxUtilisateur()
  + JPanel createTextTop() 
  + JPanel createMessagePanel()
  + JPanel createButtonValidate()
  + JPanel createCenterPanel()
  + void refreshData()
}

class CreateCache {
  - req : RequeteGeOOCache
  - descriptionTextuelle : JTextField
  - descriptionTechnique : JTextField
  - rubriqueLibre : JTextField
  - typeCacheComnbo : JComboBox<TypeCache>
  - statutCacheComnbo : JComboBox<StatutCache>
  - localisation : JTextField
  - selectionDropdown : SelectionDropdown

  + void refreshData()
}

class CreateReseau{
  - requeteGeOOCache : RequeteGeOOCache
  - inputNameReseau : JTextField
  - utilisateur : Utilisateur 

  + JPanel creerChamp() 
}

class CreateType {
  - requeteGeOOCache : RequeteGeOOCache
  - inputNameType : JTextField

  + JPanel creerChamp() 
}

class CreateUser {
  - req : RequeteGeOOCache
  - inputPseudo : JTextField
  - inputMdp : JTextField

  + JPanel creerChamp() 
}

class Footer{
  - fenetrePrincipal : FenetrePrincipal
  - cl : CardLayout
  - mainPanel : JPanel
  - requeteGeOOCache : RequeteGeOOCache
  - selectionDropdown : SelectionDropdown
  - cb : ComboBoxGeneral

  + void refreshDataView()
}

class Login{
  - fenetrePrincipal : FenetrePrincipal
  - username : JTextField 
  - password : JPasswordField
  - errorLabel : JLabel

  + JLabel createLogo()
  + JTextField createTextField()
  - JPasswordField createPasswordField() 
  - JButton createButton()
}

class ManageUser{
  - selectionDropdown : SelectionDropdown 
  - requeteGeOOCache : RequeteGeOOCache
  - listUtilisateurs : List<Utilisateur>
  - cardLayout : CardLayout
  - mainPanel : JPanel
  
  + JPanel createPanelTop()
  + JPanel createButtonBack()
  + DefaultListModel<Utilisateur> createDefaultModelUtilisateur()
  + JPanel createPanelRenderer()
  + void supprimerUtilisateur()
  + void refreshData()
}

class ShowCaches{
  - selectionDropdown : SelectionDropdown
  - requeteGeOOCache : RequeteGeOOCache
  - nomCache : JLabel
  - descriptionTextuelle : JTextArea
  - descriptionTechnique : JTextArea
  - rubriqueLibre : JTextArea
  - typeLabel : JLabel
  - statutLabel : JLabel
  - locLabel : JLabel
  
  + void refreshData()
}

class ShowListCaches{
  - selectionDropdown : SelectionDropdown 
  - requeteGeOOCache : RequeteGeOOCache
  - cl : CardLayout
  - mainPanel : JPanel
  - comboBoxGeneral : ComboBoxGeneral
  - listeCaches : JList<Cache>
  
  + DefaultListModel<Cache> createModelJListCache()
  + void refreshData()
}

class ShowLoggingDetails{
  - selectionDropdown : SelectionDropdown 
  - cardLayout : CardLayout
  - panelFenetre : JPanel
  
  + JPanel createPanel()
  + JLabel createLabel()
  + JLabel createLabelTrouve()
  + JPanel createButtonBack()
  + void refreshData()
}

class ShowLoggings{
  - requeteGeOOCache : RequeteGeOOCache
  - utilisateur : Utilisateur
  - listeLogs : JList<Log> 
  - comboBoxFiltreReseau : JComboBox<Object> 
  - comboBoxFiltreCache : JComboBox<Object> 
  - cl : CardLayout
  - mainPanel : JPanel
  - comboBoxGeneral : ComboBoxGeneral
 
  + DefaultListModel<Log> createModelJListLog()
  + DefaultComboBoxModel<Object> createModelJComboBoxReseau()
  + DefaultComboBoxModel<Object> createModelJComboBoxCache()
  + JPanel createFilterPanel()
  + void refreshData()
  + void refreshDataView()
  + JPanel createAffichageRenderer()
}





class ShowReseauMere {
  # requeteGeOOCache : requeteGeOOCache
  # utilisateur : Utilisateur 
  # mainPanel : JPanel
  # cardLayout : CardLayout
  # selectionDropdown : SelectionDropdown 
  # listReseaux : JList<ReseauCache>
  # comboBoxGeneral : ComboBoxGeneral

  + JPanel getMainPanel()
  + DefaultListModel<ReseauCache> createDefaultModelListReseauCache()
  + JPanel createPanelRenderer()
  + void actionClick()
  + void refreshDataView()
  + void refreshData()
}


class ShowReseauForCachePart {
  + JPanel createPanelRenderer()
  + void actionClick()
}

class ShowReseauForCreation {
  + JPanel createPanelRenderer()
  + void actionClick()
}

class ShowReseauStatistique {
  + JPanel createPanelRenderer()
  + void actionClick()
}

class ShowReseauUtilisateur {
  + JPanel createPanelRenderer()
  + void actionClick()
}

ShowReseauMere <|-- ShowReseauForCachePart 
ShowReseauMere <|-- ShowReseauForCreation
ShowReseauMere <|-- ShowReseauStatistique 
ShowReseauMere <|-- ShowReseauUtilisateur

class ShowStatistic {
  - requeteGeOOCache : RequeteGeOOCache
  - selectionDropdown : SelectionDropdown
  - reseauCache : ReseauCache
  - titre : JLabel
  - proprietaire : JLabel
  - nbCache : JLabel
  - nbUtilisateurs : JLabel
  - nbLogs : JLabel
  - nbTrouve : JLabel
  - nbNonTrouve : JLabel
  - pourcentage : JLabel
  - frame : JPanel
 
  + void refreshData()
}

class ShowUtilisateurs {
  - requeteGeOOCache : RequeteGeOOCache
  - utilisateur : Utilisateur
  - utilisateurs : List<Utilisateur
  - cl : CardLayout
  - mainPanel : JPanel
  - comboBoxGeneral : ComboBoxGeneral
 
  + DefaultListModel<Utilisateur> createModelJListUtilisateur()
  + void refreshData()
  + void refreshDataView()
  + JPanel createAffichageRenderer()
}


}

class FenetrePrincipal{
  - cl : CardLayout 
  - mainPanel : JPanel 
  - requeteGeOOCache : RequeteGeOOCache
  - user : Utilisateur 
  - selectionDropdown : SelectionDropdown 
  - comboBoxGeneral : ComboBoxGeneral 
  - footer : Footer

  + void loginValider()
  + void addAllView()
  + void deconnexionMainPanel()
  + void refreshMainPanel()
  + void refreshDataView()
  + RequeteGeOOCache getRequeteGeOOCache()
  + void main()
}

interface Refreshable{
  + void refreshData()
}

class SelectionDropdown{
  - elementsSelec : Map<String, Object>
  - fenetrePrincipal : FenetrePrincipal

  + void addElementSelect()
  + void supprElementSelect()
  + void supprAllElementSelect()
  + Map<String, Object> getAllElementsSelec()
  + Object getElementSelect()
}
}

package "data" #EEEEEE {
class CreerDataApplication{
  + void main()
}

}
@enduml
