@startuml

object Utilisateur{
  {static} id : int
  + pseudo : String 
  + mdp : String
  + admin : bool
}

object ReseauCache{
  {static} id : int
  + listeCaches : List<Cache>
  # <b>idProprietaire : int</b>
  + nom : String
}

object Utilisateur_reseau{
  
}

object Cache{
  {static} numero : int
  # <b>idReseau : int</b>
  + descriptionTextuelle : String
  + descriptionTechnique : String 
  + rubriqueLibre : String
  + type : TypeCache
  + listLogs : List<Log>
}

object Log{
  {static} id : int
  # <b>idCache : int</b>
  + commentaire : String
  + trouver : bool
  + date : DateTime
  + image : url /optionnel/
}

Utilisateur "0..*" - "0..*" ReseauCache 
(Utilisateur, ReseauCache) . Utilisateur_reseau

Cache::idReseau "1" -- "0..*" ReseauCache::id 

Cache::numero "0..*" - "1" Log::idCache

@enduml
